### PR TITLE
fix(fetch): fix whatwg-fetch to 2.0.4 more stable in more browser

### LINKED ISSUE #181: Fix version of whatwg-fetch
Version 3.0.0 is causing issue.

```
└─┬ @yeutech-lab/test-polyfill@1.1.3
  ├─┬ isomorphic-fetch@2.2.1
  │ └── whatwg-fetch@3.0.0 
```

For some reason, the way it is set in package.json install the 3.0, 

This ticket is for settings whatwg-fetch in the package.json

### PR DESCRIPTION
**Pull request by kopax**
FIX #181

### CODE REVIEW

**Comment by isaachinman** [comment]
Are there any plans to merge this?

**Comment by kopax** [comment]
I now use:

    npm i @yeutech-lab/isomorphic-fetch

It's what you want.

**Comment by isaachinman** [comment]
I appreciate that, but would rather not install from an unknown fork. If @matthew-andrews is not interested in maintaining the repo, they should grant active members of the community collaborator status.

**Comment by kopax** [comment]
I agree but I don't think he will reply soon. It is unknown to everyone but me, I should have release it oss sorry.

**Comment by matthew-andrews** [comment]
Sorry for the delay everyone … this is on the path to being resolved … Please test master against your applications … I wil release as a major version once I'm happy it hasn't broken anything.

**Pull request closed without merging**
