### PR TITLE
Updated dependencies to the latest versions

### PR DESCRIPTION
**Pull request by nightwolfz**
All tests pass, what else can I say?

packages.json
```
 node-fetch     1.0.1  →   1.3.3
 whatwg-fetch  0.10.0  →  0.11.0
 jshint          2.5.11  →  2.9.1
 mocha            2.1.0  →  2.3.4
 npm-prepublish   1.0.2  →  1.2.1
```

bower.json
```
"dependencies": {
    "fetch": "github/fetch#>=0.11.0"
  }
```

### CODE REVIEW

**Comment by matthew-andrews** [comment]
I don't think this does anything except potentially disrupt people who, for whatever reason, need to use old versions.  The versions that you've updated to in `dependencies` are satisfied by the previous rules…

I'd be happy to accept a pull request that just updated the `devDependencies` though.

**Comment by lucasfeliciano** [comment]
@matthew-andrews I really need this merged:

I bumped in this problem: https://github.com/facebook/react-native/issues/5667

After a long day of research I realised that is related to this issue into the github fetch module: https://github.com/github/fetch/issues/125

And if you see the changelog of the the fetch repo you find that bug fixed on version 0.11.0: https://github.com/github/fetch/releases

**Comment by matthew-andrews** [comment]
@lucasfeliciano but the previous semver should allow `v0.11.0`?

Also I think the `self` issue is currently an issue for this repo as well.

Have you tried this branch?
https://github.com/matthew-andrews/isomorphic-fetch/pull/63/files

**Comment by lucasfeliciano** [comment]
That is exactly where the problem occurs in my current version.
That is the issue ;)

**Comment by matthew-andrews** [comment]
So can I close this pull request?  I don't think this pull request does anything except potentially break this module for other consumers……

**Comment by lucasfeliciano** [comment]
The thing is, if you update the version of the `fetch` you dont need that fix.

Not 100% sure, because when I was forking to debug you replied me but yeah.

I think it is better to update the dependency than make the same changes in this repo

**Comment by matthew-andrews** [comment]
The semver constraint in the master branch for `fetch` is currently `>=0.10.0`, see:-

https://github.com/matthew-andrews/isomorphic-fetch/blob/master/bower.json#L5
https://github.com/matthew-andrews/isomorphic-fetch/blob/master/package.json

This means that when you install this module you should get the latest version of whatwg-fetch.

I have just checked this:-
```sh
$ echo {} > package.json
$ npm install --save isomorphic-fetch
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
isomorphic-fetch@2.2.1 node_modules/isomorphic-fetch
├── whatwg-fetch@0.11.0
└── node-fetch@1.3.3 (encoding@0.1.12)
```
^^ it gets whatwg-fetch@0.11.0

**Comment by lucasfeliciano** [comment]
Indeed, just checked this.

So we need this ( https://github.com/matthew-andrews/isomorphic-fetch/pull/63/files ) merged. 

Just tested it and fix the problem

**Pull request closed without merging**
