### PR TITLE
Expose Headers, Response and Request constructor globally

### PR DESCRIPTION
**Pull request by wheresrhys**
As the browser spec does.

### CODE REVIEW

**Comment by xcatliu** [comment]
Wating to be merged.

**Comment by matthew-andrews** [comment]
didn't realise this hadn't been merged.  thanks for the prompts.

**Comment by wheresrhys** [comment]
Still needs an npm release, though I also like the suggestion above https://github.com/matthew-andrews/isomorphic-fetch/pull/35#commitcomment-13413935, so perhaps that could go in the same minor?

**Comment by matthew-andrews** [comment]
can you make another PR @wheresrhys ?

**Comment by kpdecker** [comment]
Is there a timeline for publishing this to npm? It does not seem to be included in 2.2.0

**Pull request merged**
