### PR TITLE
Change usage example

### LINKED ISSUE #178: Url offline-news-api.herokuapp.com/stories not works
Url offline-news-api.herokuapp.com/stories not works

change in readme this url to another example url

### PR DESCRIPTION
**Pull request by jimmywarting**
closes #178

httpbin.org is a good api for testing
it is useful cuz you know what the request header/body you made did look like

### CODE REVIEW

**Comment by jimmywarting** [comment]
Only took a half year to press the "create pull request" button 🤣

**Comment by samrocksc** [comment]
:P Now if only you could get it approved over at npm module haha

**Comment by jimmywarting** [comment]
That will take another 6 mounts to complete

**Comment by matthew-andrews** [comment]
Sorry for the delay everyone … this is on the path to being resolved … Please test `master` against your applications … I wil release as a major version once I'm happy it hasn't broken anything.

**Comment by matthew-andrews** [comment]
Actually this is a good PR … I'm sorry it's very late but would mind undoing the undoing the whitespace change?

**Pull request closed without merging**
