### PR TITLE
Handle cases where `self` doesn't exist

### PR DESCRIPTION
**Pull request by billinghamj**
Similar to https://github.com/github/fetch/pull/253

### CODE REVIEW

**Comment by billinghamj** [comment]
GitHub's fetch has been updated now to handle this (v0.11.0 on npm).

Just need to include the equivalent change in isomorphic-fetch and certain environments (e.g. React Native) will stop crashing when including this package.

**Comment by Download** [comment]
@matthew-andrews Any update on this? Currently I fell back to using `node-fetch` on the server-side and `whatwg-fetch` on the client side because I could not get this library to work i.c.w. webpack... But I would much prefer to simply require `isomorphic-fetch` instead.

**Comment by matthew-andrews** [comment]
It feels a bit weird to fix this here.  I think this is an issue with react native rather than this library.  If react-native is going to simulate a browser-like environment then it probably should also define `self` rather than requiring fixes in other libraries don't you think?

**Comment by billinghamj** [comment]
It doesn't define a browser-like environment. It's just an entirely different environment. The main problem is the way it packages/bundles code, but that's not really changeable.

**Comment by matthew-andrews** [comment]
It must be somewhat browser-like, otherwise there would be no chance for libraries that are designed to work in browsers (like this one) would work…?

**Comment by billinghamj** [comment]
Yeah, so it actually won't be running this code at all. It has `fetch` built-in. The problem is that if I create an isomorphic library (like [json-client](https://www.npmjs.com/package/json-client)), all the dependent code is included, packaged up and the modules are parsed (not executed, just run through Babel, etc.)

The problem is that when it comes across `self`, it stops doing the packaging because it doesn't know what that is referring to.

**Comment by lucasfeliciano** [comment]
Exactly @billinghamj and @matthew-andrews .

I use in my react-native project a module that is used in a node enviroment  project and in my react project (browser) so it is breaking my react-native project.

**Comment by Download** [comment]
@matthew-andrews Isn't the whole idea for isomorphic code to be independent of environment? If the env were truly browser-like, we could just use `whatwg-fetch` directly right?

**Comment by Download** [comment]
@matthew-andrews  Oh and I am no using React Native btw. I'm using Webpack to build a module with target `umd`. But the problem is the same.

**Comment by kobenauf** [comment]
I'm having the same problem (self is not defined) on this line:
module.exports = self.fetch.bind(self);

Like previous commenters I am using webpack.  Is disposition of this "won't fix" or is it going to make it into a new isomorphic-fetch build, e.g. 2.2.2?

**Comment by Download** [comment]
Why the hesitation to merge this? It is just one line of code after all and it may make a huge difference for some of us who have commented here.

**Comment by lucasfeliciano** [comment]
I don't know, I forked it and i'm using my forked repo with the fix.
I was making this fix every time that I had to reinstall my modules.

**Comment by abuisman** [comment]
I am now having an issue with this in my react-native project. Is there a way I can implement the fix discussed above in my current project and work around this not being part of the official release yet?

**Comment by matthew-andrews** [comment]
#80 is a neater solution to this

**Comment by Download** [comment]
@matthew-andrews Will it help people like me that are not using React Native?

**Comment by matthew-andrews** [comment]
Webpack should be supported — that's how we use `isomorphic-fetch`…?

The separate entry point is to avoid the server side JS from being shipped to the client in order to keep file sizes low.  I also think using entry points is much simpler than `if`s checking the environment.

**Comment by abuisman** [comment]
@matthew-andrews Are you going to merge it and make a new release? That would be great :)

**Comment by Download** [comment]
There are multiple people in this issue reporting problems using it with Webpack. They are commenting in this specific issue because we are getting the `self is not defined` error. I use Webpack to build both the browser version as well as the NodeJS version (`target: 'node'`), maybe that's where the difference is?

There are also multiple people reporting that the fix from this issue resolves it for them. Afaict it really has *nothing* to do with React Native apart from the fact that React Native is one of the environments where `self` is not defined...

I don't mean that we should not have multiple entry points, just that an entry point specifically for React Native feels weird for me.

What would you think if you were NOT using React Native, experienced the `self is not defined` issue, only to come here, see a fix waiting for it (plus people reporting that it resolves the issue) only to have it open for a long time and finally be closed in favor of some React Native specific solution?

Please don't feel offended. I just think the original solution was great. We are talking about 2 lines of code here. It feels to me like you are overcomplicating it.

**Comment by abuisman** [comment]
I agree with @Download that it handling environments that don't have `self` is not a react-native specific fix. Even if you were to introduce an extra entry point just for react-native it might still be a good idea to handle cases where `self` is defined.

Please don't take this as pressuring you to merge something you don't want to merge, I am just adding some thoughts.

Meanwhile:
Is there a way I can use the fix in this PR? `isomorphic-fetch` is a dependency of one of my dependencies, can I tell this dependency to use the version of this PR rather than the one from npm somehow from within my project's `package.json`?

**Comment by Download** [comment]
@abuisman The only way I can think of is forking this repo, applying the patch and releasing it to NPM under a different name. Than also fork the project that is depending on this one, change it's dependency and publish that under a different name as well. Then start depending on the fork from your main project.. It's no fun.

**Comment by lucasfeliciano** [comment]
I forked this repo and I'll apply this changes.

www.github.com/lucasfeliciano/fetch-everywhere

I applied the #80 to it but after this discussion I realised that we need support ALL environments.
So I'll undo those changes and apply this patch.

**Comment by billinghamj** [comment]
It would be nice to have this existing project aim to support all environments rather than forking if possible... definitely worth giving @matthew-andrews a chance before pushing towards the fork.

**Comment by lucasfeliciano** [comment]
@billinghamj We are discussing this since Jan 11.

@matthew-andrews Said explicitly that he will not merge PR nor the other one ( react-native specific ).

Even though he merge the react-native specific fix there will be another envs which `self` will be not defined.

Saying for me, I can't wait more for this, so I decided to fork it and make target ALL environments with this new repo, doesn't matter which one since it is node based.

**Comment by billinghamj** [comment]
@lucasfeliciano sure, fair enough. It might be worth correcting to saying "all JS environments" as Node JS is just one JS environment. React, webpack, browsers, web workers, etc. are all not Node environments.

**Comment by lucasfeliciano** [comment]
@billinghamj indeed, you are right even though react, webpack and etc... works upon node js.
But your suggestion will make this clear

Other thing is you can see they are not maintaining this repo.
There is 7 PRs open with a bunch with no reply.
The same goes for issues, 19 open with a bunch with 0 reply.

**Comment by victorhqc** [comment]
@lucasfeliciano, thank you for your `fetch-everywhere` I was stuck with this :)!

**Comment by rajatrawataku1** [comment]
@billinghamj  can you help me with this. I am getting two errors : 
1. Requiring module "fetch",  which three an exception: ReferenceError: Can't find variable:self
2. Cant find variable self.

I am not able to figure out which files need to be changed and how do I change. I installed react-navigation which in turn installs isomorphic-fetch which is giving the error.

**Comment by dazjean** [comment]
After reading the discussion, I still don't understand why not merge.

**Comment by radiosilence** [comment]
This is still an issue in 2021 because it is referencing a variable `self` which doesn't exist in module level code.

**Pull request closed without merging**
